apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
  # selector uses below labels to select the pod
  selector:
    project: roboshop
    environment: dev
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008